language: cpp
sudo: false

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "ZdhRA06d6ENuY/+unOCOwi1Jr/BcDirBetQiaCM2rZtgeRluenenok5NLNsp30F89IwDV5gD9ohhw7eXiLD2SZei6UsmokLtgLUxNvecU7Vvk4b+94GQo0SWXca2c5WYf9mcvqs94zMengfU6XZVZ/zmBlT1/zlQQsN8nhM1KHQ="

before_install:
   - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "lucasdemarchi/ardupilot"
      description: "Build submitted via Travis CI"
    notification_email: lucas.de.marchi@gmail.com
    build_command_prepend: "Tools/scripts/configure_coverity.sh"
    build_command:   "Tools/scripts/build_coverity.sh"
    branch_pattern: coverity_scan
    
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - build-essential
      - gawk
      - ccache
      - genromfs
      - libc6-i386
      - libxml2-dev
      - libxslt1-dev
      - python-pip
      - python-dev
      - zlib1g-dev
      - gcc-4.9
      - g++-4.9
      - cmake
      - cmake-data

cache:
  directories:
    - $HOME/opt

before_install:
  - Tools/scripts/configure-ci.sh

before_cache:
  - ccache -z

script: true

compiler: gcc
